apiVersion: v1
kind: Service
metadata:
  name: timelogdb
  labels:
    app: timelogdb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: timelogdb
    tier: database
  clusterIP: None
