name: Apply Database kubernetes files

on:
  workflow_dispatch:
    paths:
      - 'docker/db/**'

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get version from pom.xml
        id: get_version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/db
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/timelogdb:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/timelogdb:latest
  CD:
    runs-on: ubuntu-latest
    needs: push-docker-image
    steps:
      - uses: actions/checkout@v3

      - name: Login to OpenShift
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          oc login --token=${{ secrets.OCP_TOKEN }} --server=${{ secrets.OCP_SERVER }}

      - name: Deploy to OpenShift
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          oc apply -f ./kubernetes/db/pvc.yaml
          oc apply -f ./kubernetes/db/secret.yaml
          oc apply -f ./kubernetes/db/service.yaml
          oc apply -f ./kubernetes/db/deployment.yaml